# Generated by Django 2.1.7 on 2019-02-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190225_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='branch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
