# Generated by Django 2.1.7 on 2019-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='errors',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
