# Generated by Django 2.1.7 on 2019-02-25 09:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190225_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='temp_password',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='errors',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=10100, size=100),
        ),
    ]
