# Generated by Django 2.1.7 on 2019-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190225_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='corrected_essay',
            field=models.CharField(default='', max_length=6000),
        ),
        migrations.AlterField(
            model_name='student',
            name='essay',
            field=models.CharField(default='', max_length=6000),
        ),
    ]
