# Generated by Django 2.1.7 on 2019-02-25 22:04

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190225_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='errors',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), max_length=1001000, size=100),
        ),
    ]
